package com.bookstore.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing a Review for a Book.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Review {

    /**
     * Unique identifier for the review.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer reviewId;

    /**
     * The book this review is associated with.
     */
    @ManyToOne
    @JoinColumn(name = "book_id", referencedColumnName = "bookId")
    private Book book;

    /**
     * The user who wrote the review.
     */
    @ManyToOne
    @JoinColumn(name = "reviewer_id")
    private UserEntity reviewer;

    /**
     * Rating given by the reviewer.
     * Mandatory field.
     */
    @NotNull(message = "Rating is mandatory")
    private Integer rating;

    /**
     * Text comment of the review.
     * Mandatory field.
     */
    @NotBlank(message = "Comment is mandatory")
    private String comment;

    /**
     * Timestamp of when the review was created.
     * Initialized to current date and time by default.
     */
    private LocalDateTime timestamp = LocalDateTime.now();
}
